# coding: utf-8

"""
    Apitax

    The API for the frontend of Apitax  # noqa: E501

    OpenAPI spec version: 2
    Contact: shawn.clake@nopatience.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import cli.api
from cli.api.api.any_api import AnyApi  # noqa: E501
from cli.api.rest import ApiException


class TestAnyApi(unittest.TestCase):
    """AnyApi unit test stubs"""

    def setUp(self):
        self.api = cli.api.api.any_api.AnyApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_authenticate(self):
        """Test case for authenticate

        Authenticate  # noqa: E501
        """
        pass

    def test_display_login(self):
        """Test case for display_login

        Displays the login page  # noqa: E501
        """
        pass

    def test_get_asset(self):
        """Test case for get_asset

        Displays the user dashboard page  # noqa: E501
        """
        pass

    def test_refresh_token(self):
        """Test case for refresh_token

        Refreshes login token using refresh token  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
