# coding: utf-8

"""
    Apitax

    The API for the frontend of Apitax  # noqa: E501

    OpenAPI spec version: 2
    Contact: shawn.clake@nopatience.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import cli.api
from cli.api.api.developers_api import DevelopersApi  # noqa: E501
from cli.api.rest import ApiException


class TestDevelopersApi(unittest.TestCase):
    """DevelopersApi unit test stubs"""

    def setUp(self):
        self.api = cli.api.api.developers_api.DevelopersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_script(self):
        """Test case for create_script

        Create a new script  # noqa: E501
        """
        pass

    def test_delete_script(self):
        """Test case for delete_script

        Delete a script  # noqa: E501
        """
        pass

    def test_display_developer_dashboard(self):
        """Test case for display_developer_dashboard

        Displays the developer dashboard page  # noqa: E501
        """
        pass

    def test_rename_script(self):
        """Test case for rename_script

        Rename a script  # noqa: E501
        """
        pass

    def test_save_script(self):
        """Test case for save_script

        Save a script  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
