# coding: utf-8

"""
    Apitax

    The API for the frontend of Apitax  # noqa: E501

    OpenAPI spec version: 2
    Contact: shawn.clake@nopatience.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import cli.api
from cli.api.api.users_api import UsersApi  # noqa: E501
from cli.api.rest import ApiException


class TestUsersApi(unittest.TestCase):
    """UsersApi unit test stubs"""

    def setUp(self):
        self.api = cli.api.api.users_api.UsersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_command(self):
        """Test case for command

        Execute a Command  # noqa: E501
        """
        pass

    def test_display_dashboard(self):
        """Test case for display_dashboard

        Displays the user dashboard page  # noqa: E501
        """
        pass

    def test_endpoint_catalog(self):
        """Test case for endpoint_catalog

        Retrieve the endpoint catalog  # noqa: E501
        """
        pass

    def test_get_script(self):
        """Test case for get_script

        Retrieve the contents of a script  # noqa: E501
        """
        pass

    def test_script_catalog(self):
        """Test case for script_catalog

        Retrieve the script catalog  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
