# coding: utf-8

"""
    Apitax

    The API for the frontend of Apitax  # noqa: E501

    OpenAPI spec version: 2
    Contact: shawn.clake@nopatience.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import cli.api
from cli.api.models.execute import Execute  # noqa: E501
from cli.api.rest import ApiException


class TestExecute(unittest.TestCase):
    """Execute unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testExecute(self):
        """Test Execute"""
        # FIXME: construct object with mandatory attributes with example values
        # model = cli.api.models.execute.Execute()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
