# coding: utf-8

"""
    Apitax

    The API for the frontend of Apitax  # noqa: E501

    OpenAPI spec version: 2
    Contact: shawn.clake@nopatience.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import cli.api
from cli.api.api.admins_api import AdminsApi  # noqa: E501
from cli.api.rest import ApiException


class TestAdminsApi(unittest.TestCase):
    """AdminsApi unit test stubs"""

    def setUp(self):
        self.api = cli.api.api.admins_api.AdminsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_display_admin_dashboard(self):
        """Test case for display_admin_dashboard

        Displays the developer admin page  # noqa: E501
        """
        pass

    def test_driver_status(self):
        """Test case for driver_status

        Retrieve the status of a loaded driver  # noqa: E501
        """
        pass

    def test_system_status(self):
        """Test case for system_status

        Retrieve the system status  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
