# coding: utf-8

"""
    Apitax

    The API for the frontend of Apitax  # noqa: E501

    OpenAPI spec version: 2
    Contact: shawn.clake@nopatience.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from cli.api.models.command import Command  # noqa: F401,E501
from cli.api.models.user_auth import UserAuth  # noqa: F401,E501


class Execute(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'command': 'Command',
        'auth': 'UserAuth'
    }

    attribute_map = {
        'command': 'command',
        'auth': 'auth'
    }

    def __init__(self, command=None, auth=None):  # noqa: E501
        """Execute - a model defined in Swagger"""  # noqa: E501

        self._command = None
        self._auth = None
        self.discriminator = None

        self.command = command
        if auth is not None:
            self.auth = auth

    @property
    def command(self):
        """Gets the command of this Execute.  # noqa: E501


        :return: The command of this Execute.  # noqa: E501
        :rtype: Command
        """
        return self._command

    @command.setter
    def command(self, command):
        """Sets the command of this Execute.


        :param command: The command of this Execute.  # noqa: E501
        :type: Command
        """
        if command is None:
            raise ValueError("Invalid value for `command`, must not be `None`")  # noqa: E501

        self._command = command

    @property
    def auth(self):
        """Gets the auth of this Execute.  # noqa: E501


        :return: The auth of this Execute.  # noqa: E501
        :rtype: UserAuth
        """
        return self._auth

    @auth.setter
    def auth(self, auth):
        """Sets the auth of this Execute.


        :param auth: The auth of this Execute.  # noqa: E501
        :type: UserAuth
        """

        self._auth = auth

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Execute):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
