# coding: utf-8

"""
    Apitax

    The API for the frontend of Apitax  # noqa: E501

    OpenAPI spec version: 2
    Contact: shawn.clake@nopatience.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from cli.api.models.script import Script  # noqa: F401,E501


class Rename(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'original': 'Script',
        'new': 'Script'
    }

    attribute_map = {
        'original': 'original',
        'new': 'new'
    }

    def __init__(self, original=None, new=None):  # noqa: E501
        """Rename - a model defined in Swagger"""  # noqa: E501

        self._original = None
        self._new = None
        self.discriminator = None

        self.original = original
        self.new = new

    @property
    def original(self):
        """Gets the original of this Rename.  # noqa: E501


        :return: The original of this Rename.  # noqa: E501
        :rtype: Script
        """
        return self._original

    @original.setter
    def original(self, original):
        """Sets the original of this Rename.


        :param original: The original of this Rename.  # noqa: E501
        :type: Script
        """
        if original is None:
            raise ValueError("Invalid value for `original`, must not be `None`")  # noqa: E501

        self._original = original

    @property
    def new(self):
        """Gets the new of this Rename.  # noqa: E501


        :return: The new of this Rename.  # noqa: E501
        :rtype: Script
        """
        return self._new

    @new.setter
    def new(self, new):
        """Sets the new of this Rename.


        :param new: The new of this Rename.  # noqa: E501
        :type: Script
        """
        if new is None:
            raise ValueError("Invalid value for `new`, must not be `None`")  # noqa: E501

        self._new = new

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Rename):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
